# Benchmarking
Benchmarking je metóda založená na systematickom meraní a porovnávaní vybraných ukazovateľov. Je možné ju použiť na ktorejkoľvek úrovni riadenia a pre ľubovoľné ukazovatele (indikátory). Základom je porovnávanie vybraných ukazovateľov voči iným referenčným hodnotám, ktoré môžu byť buď historické (číselný rad hodnôt 5 rokov dozadu), alebo môžu byť porovnávané voči inému referenčnému subjektu (napr. inému porovnateľnému oddeleniu alebo porovnateľnej organizácii). Najväčší prínos benchmarkingu je v tom, že rozdielne hodnoty provokujú otázky, čo je príčinou rozdielnej hodnoty a túto príčinu by mal manažment podrobiť ďalšiemu skúmaniu.

Nástroj sa zakladá na porovnávaní informácií, najčastejšie medzi organizáciami v danom sektore. Informácie sa týkajú procesov a výsledkov v určitých oblastiach. V súčasnosti sa benchmarking používa častejšie a ide aj o systematické porovnávanie charakteristík regiónov, alebo menších územných oblastí. V modernej verejnej správe sa benchmarking používa na riadenie verejných služieb a verejnej správy.

## Účel

Benchmarking môže prispieť nápadmi, ktoré zlepšia fungovanie organizácií, spokojnosť s poskytovanými verejnými službami či realizáciou intervencií. Deje sa to na základe porovnania s inými subjektami, ktoré sú považované za príklad dobrej praxe v danej oblasti. Výhodou benchmarkingu je možnosť  rozdelenia celého procesu do menších funkcií, z ktorých každá môže byť predmetom porovnania s podobnými funkciami a procesmi v iných organizáciách. V Európe sa benchmarking používa ako nástroj na zlepšenie fungovania verejného sektora, ale aj komerčných organizácií a tiež ako prostriedok na zvyšovanie konkurencieschopnosti európskej ekonomiky ako celku. 

Benchmarking je spôsob ako sa poučiť zo skúseností iných. Je to proces vzájomného učenia sa zainteresovaných organizácií, nie len jednoduchý a jednosmerný transfer ‘najlepších skúseností’ z jednej organizácie na druhú. Vo väčšom merítku môže benchmarking podporovať šírenie lepších postupov a zlepšenie výkonnosti. Aj keď bol pôvodne navrhnutý na použitie pre organizácie, môže sa využívať na hodnotenie intervencií, ale aj na porovnanie regiónov (napr. prostredníctvom ukazovateľov kvality života), alebo verejných služieb.

Benchmarking súvisí s učením sa a v tomto zmysle má niečo spoločné aj s peer review. Dá sa použiť na hodnotenie kvantitatívnych aj kvalitatívnych charakteristík. Pozostáva z identifikácie praktických postupov, procesov, opatrení alebo projektov, ktoré prispievajú k vysokej výkonnosti a využíva ich ako porovnávacie štandardy pri hodnotení iných postupov, procesov, opatrení či projektov. Dá sa využiť aj pri príprave nového programového obdobia na podporu regulačných, strategických či organizačných zmien. Tento nástroj sa dá použiť aj na zlepšenie systémov hodnotenia.

## Hlavné kroky

Benchmarking prebieha v 4 krokoch:

*1\. Identifikujeme oblasť a kritériá na možné zlepšenie.* Benchmarking zameraný na špecifické aspekty procesu, ktoré sú vybrané kvôli tomu, že sa považujú za relevantné pre oblasť alebo proces, ktorý sa má vylepšiť. Vybrané aspekty sú potom benchmarkom a pre každé kritérium je potrebné vybrať alebo skonštruovať ukazovatele.

*2\. Vyberieme inú organizáciu alebo oblasť, s ktorou budeme porovnávať.* Výber bude závisieť na oblasti, aspektoch a kritériách, ktoré vyberieme v prvom kroku. Organizácie, ktoré porovnávame majú podobnú štruktúru a pracujú v podobnom sektore, oblasti alebo kontexte a mali by byť úspešné hlavne v tých aspektoch, ktoré budeme porovnávať.

*3\. Tvorba údajov o porovnávaných organizáciách,* či hĺbková analýza akú výkonnosť majú partnerské organizácie v aspektoch, ktoré sú porovnávané a aké procesy využívajú na ich dosiahnutie, využíva návštevy v organizáciách, dotazníky, špeciálnych konzultantov alebo panely pozostávajúce zo zástupcov partnerov.

*4\. Porovnanie postupov a výkonnosti partnerských organizácií* sa pokúša identifikovať vzťah medzi postupom a výkonnosťou a hľadá možnosti zmeny postupov, ktorý by zlepšili výkonnosť. Ak sú medzi partnermi dobré vzťahy, proces benchmarkingu sa dá znova opakovať v inej oblasti, kde by mohlo byť porovnanie užitočné. Takýmto spôsobom sa môže vytvoriť vzájomne výhodné partnerstvo založené na spoločnom učení sa.

Tieto štyri kroky môžu mať veľa rôznych foriem. V niektorých prípadoch je to len porovnanie výstupov a výsledkov dosiahnutých organizáciami. Sústreďuje sa to na hodnotenie, v ktorom sa výkonnosť prezentuje v rebríčku. Čoraz častejšie však organizácie používajú benchmarking ako diagnostický nástroj, ktorý umožňuje programovým manažérom nie len vidieť rozdiely, ale aj analyzovať ich príčiny a učiť sa navzájom spolu s partnermi stratégie, ktoré ju zlepšia. Tento prístup je známy ako ‘procesný benchmarking’. Vyžaduje si analýzu rôznych štýlov riadenia, organizačných kultúr a environmentálnych kontextov, v ktorých intervencie fungujú ako aj nástrojov na realizáciu politík. Benchmarking má schopnosť identifikovať postupy, ktoré vedú k dobrej výkonnosti, preniesť ich a prispôsobiť inému prostrediu.

Často sa tvrdí, že najlepšie je porovnanie medzi podobnými intervenciami, ktoré fungujú v podobnom prostredí, pretože ich výkonnosť a postupy sa dajú v mnohých aspektoch porovnávať. Nie vždy to však platí, a niektorí manažéri zistili, že môžu získať veľa nového aj z benchmarkingu voči organizáciám, ktoré sú odlišné alebo fungujú na podobných postupoch, ale v odlišnom kontexte. Výmena informácií medzi organizáciami vo verejnom, súkromnom či treťom sektore prezentuje čoraz častejší príklad tohto prístupu. V kontexte EŠIF môže byť príkladom benchmarkingu porovnanie  fungovania podobných intervencií v rôznych členských štátoch alebo porovnanie EU financovaných intervencií s domácimi iniciatívami v tej istej krajine.

## Silné stránky a obmedzenia

Benchmarking je užitočná a flexibilná metóda založená na porovnaní, ktoré sa dá využiť na tvorbu riešení organizačných problémov a zvýrazniť silné stránky aj nápady na zlepšenie; môže zlepšiť meranie výkonnosti. Dá sa využiť na kreatívne myslenie o interných procesoch a ich vzťahoch k výkonnosti. Vo svojej podstate zlepšuje vzťahy medzi dvoma alebo viacerými organizáciami a v tomto zmysle podporuje spoluprácu. Môže byť katalyzátorom na tvorbu dynamických, dlhodobých  a vzájomne výhodných vzťahov s inými organizáciami, založených na dôvere a vzájomnom učení sa.

Benchmarking je často založený na zdieľaní strategických informácií. Môže preto predstavovať komerčné alebo politické riziko, s ktorým treba opatrne narábať. Zle urobený benchmarking  môže mať negatívny dopad na organizáciu a jej vzťahy s partnermi, napr. tým, že podporí napodobňovanie a obmedzí inovácie. Intervencia zvyčajne funguje raz na nejakom mieste, neznamená, že sa dá rovnako použiť kdekoľvek. Aby bol benchmarking čo najefektívnejší vyžaduje si participatívny prístup. Ak sa vykonáva bez skutočnej účasti organizácie, bude mať na organizáciu minimálny dopad.