# Ďalšie používané nástroje a metódy
Hodnotenie využíva aj mnoho ďalších nástrojov a metód, ktoré sú pre túto činnosť menej bežné  a sú „požičané“ z iných oblastí ako je napr. audit, manažment, či štatistika. V závislosti od konkrétneho zadania či hodnotiacej otázky je dobré posúdiť, či využitie takýchto nástrojov nie je  vhodné. Takéto nástroje sú inováciami v oblasti hodnotenia, ale na konkrétne zadanie, či úlohu môžu byť optimálne. Množstvo inovácií prichádza s fenoménom sociálnych sietí a obrovského súboru údajov, ktoré tieto siete zbierajú, často na marketingové účely. Rovnako ako v marketingu, aj vo verejných politikách majú takto zbierané údaje potenciál ovplyvňovať konanie ľudí. Samostatnú kapitolu tvoria aj nástroje, ktoré umožňujú interakciu so špeciálnymi skupinami, či už ide o znevýhodnené skupiny, alebo napr. o skupiny domorodých obyvateľov v rámci krajín rozvojovej pomoci kde je problémom v komunikácii nie len jazyk, či gramotnosť respondentov, ale aj kultúrne zvyklosti a hodnoty týchto spoločenstiev.

Na ilustráciu uvádzame niekoľko príkladov, ktoré sa vyskytli v plánoch hodnotení operačných programov EŠIF.  

## Procesná analýza

Väčšina hodnotení je vzhľadom na pomalý progres v implementácii operačných programov na Slovensku zameraná práve na hodnotenie procesov, ktoré je však pomerne často len parciálne. Systémová zmena si zvyčajne žiada dôkladnejšiu analýzu a vhodným nástrojom na takéto riešenie môže byť procesná analýza.

Ak chceme zdokonaliť systém zlepšením procesov, musíme sa s nimi oboznámiť, zanalyzovať ich a porozumieť im. Toto sa deje v procesnej analýze, ktorá posudzuje, ako dobre proces dosahuje svoj konečný cieľ. Analýza procesov identifikuje a skúma celý systém vrátane samotných procesov, zúčastnených strán, výmeny informácií a ďalších sprievodných aktivít. V súlade s tým môže pomôcť identifikovať potenciálne zlepšenia v rámci procesu. Vo väčšine prípadov môže byť analýza procesov užitočná pri hľadaní dôvodov, ktoré spôsobujú systematické úzke miesta a procesy trvajú neúmerne dlho; alebo pri určení, či proces pracuje alebo nepracuje na maximálnej potenciálnej kapacite a zisťovaní, či by sa mal vylepšiť alebo prepracovať.

Procesná analýza je štandardne činnosť zameraná na preskúmanie a pochopenie obchodných procesov. Zahŕňa preskúmanie komponentov procesu vrátane vstupov, výstupov, postupov, kontrolných mechanizmov, aktérov, aplikácií, údajov, technológií a ich interakcií s cieľom dosiahnuť výsledky. Štandardný postup začína identifikáciou procesov a vytvorením vývojových diagramov procesov. Táto technika analýzy procesu je veľmi užitočná, lebo poskytuje grafické znázornenie pomocou štandardných symbolov a nástrojov. Následne sa definujú zodpovedné osoby, ich zodpovednosti/úlohy a ich vzťahy. Definujeme tak priebeh procesu so všetkými vyššie uvedenými informáciami na základe rozhovorov s aktérmi. Procesný model analyzujeme, zistíme, aký je účel procesu, aké metriky výkonu sa používajú, aké existujú interakcie - odovzdanie práce alebo informácií od jednej osoby, tímu alebo systému druhej osobe, aké pravidlá sa uplatňujú, kde sú úzke miesta, ako sa proces riadi. Na základe analýzy sa určia potrebné a možné vylepšenia. Pritom sa vždy zohľadňuje, že všetky procesy a činnosti musia byť vedené tak, aby naplnili svoje ciele. Návrh nového vylepšeného procesu, ktorý vznikne na základe analýzy by tak mal umožniť efektívnejšie a účinnejšie dosahovanie cieľov.

## Riziková analýza

Riziká sú všetko, čo môže potenciálne narušiť akékoľvek plánované činnosti. Analýza rizík je proces, ktorý zisťuje pravdepodobnosť vzniku rizika v intervencii a je nástrojom, ktorý môže pomôcť identifikovať a analyzovať potenciálne problémy, ktoré by mohli narušiť plán. Analýza rizík je užitočný rozhodovací nástroj, pretože identifikuje riziká, ponúka alternatívy a umožňuje rozhodnúť sa, či napredovať, príp. po identifikácii potenciálnych rizík sa môžeme rozhodnúť, ako ich najlepšie riadiť.

Riziko sa skladá z dvoch častí: pravdepodobnosti, že sa niečo pokazí, a negatívnych dôsledkov, ak sa to stane. Ak chceme realizovať analýzu rizík, musíme najskôr identifikovať možné hrozby, ktorým čelíme, a potom odhadnúť pravdepodobnosť, že sa tieto hrozby prejavia. Riadenie rizík zahŕňa identifikáciu rizika, hodnotenie rizika, vývoj reakcie na riziko a kontrolu reakcie na riziko. Proces hodnotenia rizika projektu sa začína vo fázach plánovania, musí však pokračovať v každej fáze intervencie.

Existuje množstvo spôsobov, nástrojov a metód na meranie rizika, ktorá sa väčšinou viažu na typ rizika. Najbežnejšie sa v projektoch riziko odhaduje v dvoch parametroch. Jeden odhaduje pravdepodobnosť, že sa v intervencii vyskytne nejaké riziko najčastejšie na stupnici od 0 do 1, alebo v percentách od 0 do 100. Druhým parametrom je veľkosť rizika, napr. niekedy na stupnici od 1 do 3, ale škálu si každý môže zvoliť. Z týchto dvoch parametrov celkový súčin určuje veľkosť rizika. Niekedy existuje aj stupnica vplyvu. Riziko bude následne kategorizované buď na základe zdrojov alebo účinkov. Analýza rizík je užitočná v mnohých situáciách: pri plánovaní projektov vám pomôže predvídať možné problémy, pri rozhodovaní, či v projekte pokračovať alebo nie.

Pri analýze rizík sa začína identifikáciou hrozby (môže sa týkať ľudských zdrojov, prevádzky, reputácie, procedúr, financií, prírodných úkazov, ...). Môžeme použiť SWOT analýzu, ktorá umožňuje zostaviť zoznam interných a externých faktorov, ktoré by mohli mať vplyv na intervenciu. Odhadneme riziko - každá neistota má odhadovaný vplyv a určíme, ako závažný môže byť. Keď  je  identifikovaný zdroj rizika a miera neistoty, ktorá s nimi súvisí, môžeme odhadnúť účinok. Jednou z ďalších metód je výpočet pravdepodobnosti výskytu udalosti a vynásobenie cenou udalosti, aby sme odhadli hodnotu rizika. Kompletný model môžeme vytvoriť zostavením všetkých vstupov, ktoré predstavujú neistotu. Zhrnieme výsledky pomocou tabuľky alebo grafu, nájdeme riešenie s najmenšou mierou rizika a implementujeme ho.

## Analýza časových radov

Pri dostupnosti dostatočného množstva údajov je možné z trendov dobre vidieť ako sa sledovaný parameter v čase vyvíja. Tieto údaje sa zaznamenávajú v časových radoch. Časový rad je súbor pozorovaní presne definovaných údajov získaných prostredníctvom opakovaného merania v určitom čase. Časové rady sa líšia podľa časovej zložky, v závislosti od toho nám indikujú zmenu napr. z hľadiska trendov (dlhodobé smerovanie), alebo sezónne zmeny, či nepravidelné cykly (nesystematické, krátkodobé výkyvy). Časové rady sa často názorne zobrazujú na grafoch. Časové rady majú dva hlavné ciele: identifikovať povahu javu, ktorú reprezentuje súbor pozorovaní v čase, a predpovedať budúce hodnoty premennej v časovom rade. Oba tieto ciele vyžadujú, aby bol identifikovaný model pozorovaných údajov časových radov a aby bol tento model nejako formálne popísaný. Minimálny počet pozorovaní pre časové rady je aspoň dvadsať.

Účelom časových radov je preskúmať a zaznamenať údaje, ktoré sú merané vždy rovnakým spôsobom a pravidelne v rôznych časových obdobiach (za sezónu, rok, mesiac alebo dokonca týždeň), aby sme v priebehu času zaznamenali cyklické zmeny. Z pohľadu monitorovania a hodnotenia môže takýto „vývoj v čase“ pomôcť napríklad pri hodnotení, ktoré rieši, či pravidelne sa vyskytujúce úzke miesta možno pripísať projektu. Tento nástroj je veľmi vhodný na monitorovanie a hodnotenie výkonnostných otázok, resp. ukazovateľov. Je samozrejme dôležité zohľadniť v akom časovom intervale je možné sledovať zmeny, či to bude na týždennej, mesačnej, alebo ročnej báze. Záleží to od konkrétneho vybraného ukazovateľa a od toho ako rýchlo sa mení.

Pri monitorovaní si môžeme zostaviť rozpis v trvaní jedného alebo niekoľkých rokov, prípadne mesiacov alebo ročných období, v ktorých sa má meranie uskutočniť. V niektorých prípadoch toto monitorovanie prebieha na pravidelných týždenných alebo mesačných schôdzkach zamestnancov, kde sa robí odpočet úloh dokončených za posledný mesiac. Údaje sa zhromažďujú aj inými prostriedkami, často to môže byť aj údaj pravidelne zaznamenávaný ako štatistický ukazovateľ. V pravidelnom časovom intervale, za celé obdobie kedy sa údaje zhromažďujú, je potrebné vždy zaznamenať potrebný údaj. Môže sa stať, že údaje sa získavajú aj prostredníctvom skupinovej diskusie. Každá skupina si vyberie jedného alebo dvoch „kľúčových informátorov“, ktorí majú príslušné odborné znalosti, s ktorými pohovorí zvyšok skupiny. Na základe týchto informácií potom každá skupina vytvorí diagram na ilustráciu trendov a zmien v týchto činnostiach a / alebo udalostiach v sledovanom časovom intervale. Výsledky sa potom predkladajú celej skupine na diskusiu.

V niektorých prípadoch bude priebeh zmien v čase slúžiť na diskusiu, ktorá by mala viesť k pochopeniu o aké zmeny ide a prečo k nim dochádza. Súčasným monitorovaním rôznych údajov v rovnakom časovom úseku (alebo na trendovom grafe) sa môžu prejaviť určité vzorce, napríklad to, ako sa mení vnímanie niektorých faktorov v obdobiach zadlžovania, alebo chorôb. Údaje je v niektorých prípadoch možné diferencovať aj podľa veku a pohlavia. Relevantnosť takýchto variácií však bude závisieť od toho, čo potrebujeme monitorovať.

Variáciou tejto možnosti je napr. znázornenie denných rutín (ako trávim svojich 24 hodín), čiže sledovanie denných vzorcov. Je to užitočné pri hodnotení kľúčových prekážok pri každodenných úlohách a spôsobe, ako ich možno prekonať, alebo pri hodnotení práce a vstupov potrebných pre každodenné úlohy. Porovnáva sa súčasná situácia s predchádzajúcimi diagramami. Zisťujeme ako sú bežné postupy ovplyvnené zmenami, ktoré sme zaviedli. Podobne môže takéto sledovanie fungovať pre konkrétne časové obdobie/ sezónu. Ak sledujeme celý rad ukazovateľov, tieto môžu odhaliť prepojenie rôznych vzorcov zmien a môžu slúžiť aj na diskusiu o kauzálnych súvislostiach určitých zmien. V projektoch rozvojovej pomoci môžu poslúžiť na sledovanie faktorov ovplyvňujúcich napr. zásoby vody, alebo chorobnosť. Aj keď sú k dispozícii historické údaje, v týchto prípadoch môže byť potrebná aj krížová kontrola prostredníctvom priameho merania napríklad času potrebného na načerpanie vody alebo výskyt chorôb. V prípade, že sa tento nástroj používa pre skupinu ľudí, môže byť náročné určiť, čo je priemerná každodenná rutina. Je preto lepšie ak je záznam robený individuálne a potom sa analyzujú rôzne postupy spoločne, pričom je potrebné venovať pozornosť skresleniam.

## Faktorová analýza

Faktorová analýza je štatistická metóda, ktorá na základe vzájomných vzťahov medzi viacerými premennými identifikuje spolu vzájomne súvisiace premenné. Premenné, ktoré skúma a ktorých je zvyčajne veľa, sa označujú pojmom manifestné premenné.  Z týchto vzájomne úzko súvisiacich premenných vytvára faktory, čím redukuje počet premenných do menšieho počtu faktorov. Tieto zredukované premenné sa nazývajú latentné premenné.   Čiže faktorová analýza redukuje počet premenných cez skúmanie vzájomných vzťahov medzi manifestnými premennými a identifikuje v skupine premenných latentné premenné - faktory. Faktorová analýza sa prakticky používa na zistenie vzájomných vzťahov medzi premennými, pri tvorbe dotazníkov, alebo pri redukcii  veľkého počtu premenných na obmedzený počet faktorov.

Predstavme si, že chceme skúmať určité premenné, na ktoré sa nevieme spýtať priamo jednou otázkou, ale len prostredníctvom viacerých iných otázok. K takýmto premenným patria napríklad osobnostné črty ako je introverzia,  úzkosť,  depresia alebo intuícia. Zistenie ako je človek introvertný, úzkostný, alebo intuitívny nevieme urobiť na základe jednej otázky.  Zvyčajne musíme človeku položiť viacero otázok, niekedy celý dotazník,  aby sme si spravili obraz o týchto pozorovaných charakteristikách. Takže napr. intuícia je v tomto prípade latentná premenná – faktor, túto premennú meriame pomocou viacerých iných otázok v dotazníku, ktoré v tomto prípade nazývame manifestné premenné.

## Využitie štatistických údajov

V hodnotení sa pomerne často pracuje so štatistickými údajmi. K takýmto údajom patria dáta, ktoré sa pravidelne v stanovenom intervale zbierajú jednotnou metodikou nie len na národnej úrovni, ale niekedy aj v rámci všetkých členských štátov EÚ, alebo túto činnosť zastrešuje iná medzinárodná organizácia. K takto získaným údajom patria napr. aj dáta z výberového zisťovania pracovných síl, ktoré môžu plniť úlohu kontextových ukazovateľov a súčasne slúžia na porovnanie s inými štátmi.

**Výberové zisťovanie pracovných síl**

Metóda výberového zisťovania pracovných síl v domácnostiach je štandardnou metódou odporúčanou medzinárodnými inštitúciami pod patronátom Medzinárodnej organizácie práce (ILO). Legislatívnym základom pre vykonávanie tohto zisťovania v členských krajinách Európskej únie je Nariadenie rady (ES) c. 577/98 o organizácii výberového zisťovania pracovných síl v Spoločenstve. Výberové zisťovanie pracovných síl prebieha na území Slovenskej republiky nepretržite od začiatku roka 1993, pričom od roku 2006 je zabezpečená úplná harmonizácia zisťovania s príslušnými právnymi predpismi Európskej únie. Cieľom zisťovania je zabezpečovať pravidelné informácie o stave, štruktúre a vývoji trhu práce v SR na báze rovnakého metodického prístupu k meraniu zamestnanosti, nezamestnanosti a ekonomickej neaktivity. Výsledky zisťovania ponúkajú širokú škálu informácií, ktoré sú zverejňované so štvrťročnou periodicitou.

Výberové zisťovanie pracovných síl je prieskum realizovaný Štatistickým úradom Slovenskej republiky. Je jednou z metód pre kvantifikáciu miery zamestnanosti a nezamestnanosti. Tento zdroj je používaný aj štatistickým úradom EÚ - Eurostatom na porovnanie charakteristík trhov práce členských krajín.

Do prieskumu je zaradených približne 10 tisíc domácností, čo predstavuje cca 30 tisíc respondentov. Títo zostávajú v súbore 5 po sebe idúcich štvrťrokov, a potom sú z neho vylúčení a nahradení inými. Toto sa deje priebežne, takže v každom období je v súbore 1/5 respondentov po prvý krát. Respondenti sú dotazovaní pracovníkmi Štatistického úradu SR pri osobnom kontakte.